# General settings
[logging]
log_to_file = false # Enable/disable logging to a file (named <program>.log)
                    # Tip: on linux logging to the systemd journal is supported
stdout_debug = false # Enable debug logging level on stdout
file_debug = false # Enable debug logging level on the log file (if enabled)
                   # Note: not recommended, as debug log logs a lot of data
journal_debug = false # Enable debug logging level on the systemd journal (if enabled)

[autorx]
host = "" # Autorx host. Leave this empty if autorx is configured to broadcast
port = 55673 # UDP port that autorx sends its payload summaries to

[station]
latitude = 0.0 # Latitude of your receiver
longitude = 0.0 # Longitude of your receiver

[notifier]
check_interval = 1 # Interval in minutes between checks if notifications should be sent

# Define as many range rings as you'd like
range_rings = [
    # Radius and maximum altitude are in kilometers
    # If a range ring gets triggerd by a sonde, all range rings below it in this list
    # will also be counted as triggered, so order them so that the largest ones are at the bottom
    # and the smallest ones at the top of the list.
    { name = "inner", radius = 10, max_altitude = 3, only_descending = true },
    { name = "outer", radius = 50, max_altitude = 8, only_descending = true }
]

[prediction]
enabled = true
prediction_cycles = 15 # How many times the notifier check interval needs to be completed to run a prediction
                       # (Every Nth run of the notification check will try to run a prediction)
api_url = "https://api.v2.sondehub.org/tawhiri" # URL to the prediction API.
                                                # I highly recommend self-hosting this,
                                                # to prevent leeching off of sondehubs resources.
                                                # (https://github.com/projecthorus/tawhiri)
only_predict_descending = true # Only run prediction for sondes that are descending.
                               # Recommended, as predictions are usually a lot more accurate
                               # when sondes are descending
ascent_rate = 5 # Ascent rate in m/s for prediction
burst_altitude = 30 # Burst altitude in km for prediction
descent_rate = 10 # Descent rate in m/s for prediction


# Notification services
[email]
enabled = false
smtp_host = "smtp.example.com"
smtp_port = 465
smtp_auth = "ssl" # Options: none or ssl
smtp_login = "myemail@example.com"
smtp_password = "sup3r_s3cr3t_p4ssword"
sender = "myemail@example.com"
destinations = ["otheremail@example.com"]

[ntfy]
enabled = false
topic_url = "https://ntfy.sh/..."
auth_user = ""
auth_password = ""
auth_token = "" # Auth token (overrides user&password if set)

[gotify] # untested
enabled = false
url = "https://example.com/"
app_token = ""

[discord_webhook]
enabled = false
url = "https://discord.com/api/webhooks/..."
mentions = "<@userid1> <@userid2>"
